# Generated by Django 3.2.5 on 2022-06-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('url', models.URLField(blank=True)),
                ('release_date', models.DateField()),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
