# Generated by Django 3.2.5 on 2022-06-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorushika', '0002_alter_song_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='text',
            field=models.TextField(max_length=150),
        ),
    ]
