# Generated by Django 3.2.5 on 2022-06-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorushika', '0003_alter_song_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='images')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
