# Generated by Django 3.2.5 on 2022-06-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorushika', '0004_auto_20220607_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
