# Generated by Django 3.2.5 on 2022-06-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorushika', '0008_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
