# Generated by Django 3.2.5 on 2022-06-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorushika', '0009_song_song_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='text',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
