# Generated by Django 3.2.5 on 2022-06-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorushika', '0010_alter_song_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanctuary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanctuary', models.CharField(max_length=150)),
                ('song', models.CharField(max_length=150)),
                ('text', models.TextField(blank=True, max_length=150)),
                ('tag', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
