# Generated by Django 3.2.5 on 2022-06-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorushika', '0013_remove_sanctuary_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctuary',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
