# Generated by Django 3.2.5 on 2022-06-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorushika', '0015_alter_sanctuary_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctuary',
            name='tag',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
