# Generated by Django 3.2.5 on 2022-07-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorushika', '0016_alter_sanctuary_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='display_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
