# Generated by Django 3.2.5 on 2023-01-29 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yorushika', '0020_auto_20220718_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='highlighted',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='auth.user'),
            preserve_default=False,
        ),
    ]
