# Generated by Django 3.2.5 on 2023-01-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorushika', '0021_auto_20230129_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='highlighted',
            field=models.TextField(blank=True),
        ),
    ]
